.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH boilertex-preview 1  "boilertex-preview " 
.SH NAME
boilertex\-preview
.SH SYNOPSIS
\fBboilertex preview\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITEMPLATE\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITEMPLATE\fR>
The name of the template to be previewed
