.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH boilertex-list 1  "boilertex-list " 
.SH NAME
boilertex\-list \- List the templates in your config
.SH SYNOPSIS
\fBboilertex list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List the templates in your config
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
